// Comprehensive niche database organized by industry
export interface Niche {
  id: string;
  name: string;
  category: string;
  description?: string;
}

export interface IndustryCategory {
  id: string;
  name: string;
  emoji: string;
  description: string;
  niches: Niche[];
}

export const FORGE_INDUSTRY_CATEGORIES: IndustryCategory[] = [
  {
    id: 'business_marketing',
    name: 'Business & Marketing',
    emoji: '📈',
    description: 'Marketing, consulting, and business services',
    niches: [
      { id: 'marketing_agencies', name: 'Marketing Agencies', category: 'business_marketing' },
      { id: 'social_media_management', name: 'Social Media Management', category: 'business_marketing' },
      { id: 'content_creation_studios', name: 'Content Creation Studios', category: 'business_marketing' },
      { id: 'email_marketing_services', name: 'Email Marketing Services', category: 'business_marketing' },
      { id: 'seo_consulting', name: 'SEO Consulting', category: 'business_marketing' },
      { id: 'brand_strategy', name: 'Brand Strategy', category: 'business_marketing' },
      { id: 'digital_marketing', name: 'Digital Marketing', category: 'business_marketing' },
      { id: 'ppc_advertising', name: 'PPC Advertising', category: 'business_marketing' },
      { id: 'copywriting_services', name: 'Copywriting Services', category: 'business_marketing' },
      { id: 'video_marketing', name: 'Video Marketing', category: 'business_marketing' },
      { id: 'influencer_marketing', name: 'Influencer Marketing', category: 'business_marketing' },
      { id: 'affiliate_marketing', name: 'Affiliate Marketing', category: 'business_marketing' },
      { id: 'growth_hacking', name: 'Growth Hacking', category: 'business_marketing' },
      { id: 'conversion_optimization', name: 'Conversion Rate Optimization', category: 'business_marketing' },
      { id: 'marketing_analytics', name: 'Marketing Analytics', category: 'business_marketing' },
      { id: 'public_relations', name: 'Public Relations', category: 'business_marketing' },
      { id: 'crisis_management', name: 'Crisis Management', category: 'business_marketing' },
      { id: 'event_marketing', name: 'Event Marketing', category: 'business_marketing' },
      { id: 'market_research', name: 'Market Research', category: 'business_marketing' },
      { id: 'competitive_analysis', name: 'Competitive Analysis', category: 'business_marketing' },
      { id: 'customer_segmentation', name: 'Customer Segmentation', category: 'business_marketing' },
      { id: 'lead_generation', name: 'Lead Generation', category: 'business_marketing' },
      { id: 'sales_funnel_optimization', name: 'Sales Funnel Optimization', category: 'business_marketing' },
      { id: 'account_based_marketing', name: 'Account-Based Marketing', category: 'business_marketing' },
      { id: 'partner_marketing', name: 'Partner Marketing', category: 'business_marketing' },
      { id: 'product_marketing', name: 'Product Marketing', category: 'business_marketing' },
      { id: 'b2b_marketing', name: 'B2B Marketing', category: 'business_marketing' },
      { id: 'b2c_marketing', name: 'B2C Marketing', category: 'business_marketing' },
      { id: 'startup_marketing', name: 'Startup Marketing', category: 'business_marketing' },
      { id: 'enterprise_marketing', name: 'Enterprise Marketing', category: 'business_marketing' },
      { id: 'local_business_marketing', name: 'Local Business Marketing', category: 'business_marketing' },
      { id: 'ecommerce_marketing', name: 'E-commerce Marketing', category: 'business_marketing' },
      { id: 'saas_marketing', name: 'SaaS Marketing', category: 'business_marketing' },
      { id: 'mobile_app_marketing', name: 'Mobile App Marketing', category: 'business_marketing' },
      { id: 'podcast_marketing', name: 'Podcast Marketing', category: 'business_marketing' },
      { id: 'webinar_services', name: 'Webinar Services', category: 'business_marketing' },
      { id: 'community_management', name: 'Community Management', category: 'business_marketing' },
      { id: 'reputation_management', name: 'Reputation Management', category: 'business_marketing' },
      { id: 'review_management', name: 'Review Management', category: 'business_marketing' },
      { id: 'referral_programs', name: 'Referral Programs', category: 'business_marketing' },
      { id: 'loyalty_programs', name: 'Loyalty Programs', category: 'business_marketing' },
      { id: 'customer_retention', name: 'Customer Retention', category: 'business_marketing' },
      { id: 'brand_positioning', name: 'Brand Positioning', category: 'business_marketing' },
      { id: 'messaging_strategy', name: 'Messaging Strategy', category: 'business_marketing' },
      { id: 'go_to_market_strategy', name: 'Go-to-Market Strategy', category: 'business_marketing' },
      { id: 'product_launch_services', name: 'Product Launch Services', category: 'business_marketing' },
      { id: 'rebranding_services', name: 'Rebranding Services', category: 'business_marketing' },
      { id: 'business_consulting', name: 'Business Consulting', category: 'business_marketing' },
      { id: 'strategy_consulting', name: 'Strategy Consulting', category: 'business_marketing' },
      { id: 'operations_consulting', name: 'Operations Consulting', category: 'business_marketing' },
    ],
  },
  {
    id: 'technology_software',
    name: 'Technology & Software',
    emoji: '💻',
    description: 'Software development, IT services, and tech consulting',
    niches: [
      { id: 'web_development', name: 'Web Development', category: 'technology_software' },
      { id: 'mobile_app_development', name: 'Mobile App Development', category: 'technology_software' },
      { id: 'software_consulting', name: 'Software Consulting', category: 'technology_software' },
      { id: 'cloud_migration', name: 'Cloud Migration', category: 'technology_software' },
      { id: 'devops_services', name: 'DevOps Services', category: 'technology_software' },
      { id: 'cybersecurity_consulting', name: 'Cybersecurity Consulting', category: 'technology_software' },
      { id: 'it_support_services', name: 'IT Support Services', category: 'technology_software' },
      { id: 'network_management', name: 'Network Management', category: 'technology_software' },
      { id: 'database_administration', name: 'Database Administration', category: 'technology_software' },
      { id: 'system_integration', name: 'System Integration', category: 'technology_software' },
      { id: 'api_development', name: 'API Development', category: 'technology_software' },
      { id: 'blockchain_development', name: 'Blockchain Development', category: 'technology_software' },
      { id: 'ai_ml_consulting', name: 'AI/ML Consulting', category: 'technology_software' },
      { id: 'data_science_services', name: 'Data Science Services', category: 'technology_software' },
      { id: 'big_data_analytics', name: 'Big Data Analytics', category: 'technology_software' },
      { id: 'business_intelligence', name: 'Business Intelligence', category: 'technology_software' },
      { id: 'crm_implementation', name: 'CRM Implementation', category: 'technology_software' },
      { id: 'erp_consulting', name: 'ERP Consulting', category: 'technology_software' },
      { id: 'saas_development', name: 'SaaS Development', category: 'technology_software' },
      { id: 'platform_engineering', name: 'Platform Engineering', category: 'technology_software' },
      { id: 'quality_assurance_testing', name: 'Quality Assurance Testing', category: 'technology_software' },
      { id: 'automation_testing', name: 'Automation Testing', category: 'technology_software' },
      { id: 'performance_testing', name: 'Performance Testing', category: 'technology_software' },
      { id: 'security_testing', name: 'Security Testing', category: 'technology_software' },
      { id: 'ui_ux_design', name: 'UI/UX Design', category: 'technology_software' },
      { id: 'product_design', name: 'Product Design', category: 'technology_software' },
      { id: 'prototyping_services', name: 'Prototyping Services', category: 'technology_software' },
      { id: 'technical_documentation', name: 'Technical Documentation', category: 'technology_software' },
      { id: 'code_review_services', name: 'Code Review Services', category: 'technology_software' },
      { id: 'legacy_system_modernization', name: 'Legacy System Modernization', category: 'technology_software' },
      { id: 'microservices_architecture', name: 'Microservices Architecture', category: 'technology_software' },
      { id: 'serverless_computing', name: 'Serverless Computing', category: 'technology_software' },
      { id: 'iot_development', name: 'IoT Development', category: 'technology_software' },
      { id: 'ar_vr_development', name: 'AR/VR Development', category: 'technology_software' },
      { id: 'game_development', name: 'Game Development', category: 'technology_software' },
      { id: 'elearning_platforms', name: 'E-learning Platforms', category: 'technology_software' },
      { id: 'lms_development', name: 'LMS Development', category: 'technology_software' },
      { id: 'chatbot_development', name: 'Chatbot Development', category: 'technology_software' },
      { id: 'voice_assistant_development', name: 'Voice Assistant Development', category: 'technology_software' },
      { id: 'computer_vision_services', name: 'Computer Vision Services', category: 'technology_software' },
      { id: 'natural_language_processing', name: 'Natural Language Processing', category: 'technology_software' },
      { id: 'predictive_analytics', name: 'Predictive Analytics', category: 'technology_software' },
      { id: 'recommendation_engines', name: 'Recommendation Engines', category: 'technology_software' },
      { id: 'fraud_detection_systems', name: 'Fraud Detection Systems', category: 'technology_software' },
      { id: 'payment_gateway_integration', name: 'Payment Gateway Integration', category: 'technology_software' },
      { id: 'fintech_solutions', name: 'Fintech Solutions', category: 'technology_software' },
      { id: 'insurtech_solutions', name: 'Insurtech Solutions', category: 'technology_software' },
      { id: 'healthtech_solutions', name: 'Healthtech Solutions', category: 'technology_software' },
      { id: 'edtech_solutions', name: 'Edtech Solutions', category: 'technology_software' },
      { id: 'proptech_solutions', name: 'Proptech Solutions', category: 'technology_software' },
    ],
  },
  {
    id: 'health_wellness',
    name: 'Health & Wellness',
    emoji: '💪',
    description: 'Fitness, nutrition, mental health, and wellness services',
    niches: [
      { id: 'personal_training', name: 'Personal Training', category: 'health_wellness' },
      { id: 'nutrition_coaching', name: 'Nutrition Coaching', category: 'health_wellness' },
      { id: 'weight_loss_programs', name: 'Weight Loss Programs', category: 'health_wellness' },
      { id: 'yoga_instruction', name: 'Yoga Instruction', category: 'health_wellness' },
      { id: 'pilates_training', name: 'Pilates Training', category: 'health_wellness' },
      { id: 'crossfit_coaching', name: 'CrossFit Coaching', category: 'health_wellness' },
      { id: 'sports_performance', name: 'Sports Performance', category: 'health_wellness' },
      { id: 'rehabilitation_services', name: 'Rehabilitation Services', category: 'health_wellness' },
      { id: 'physical_therapy', name: 'Physical Therapy', category: 'health_wellness' },
      { id: 'occupational_therapy', name: 'Occupational Therapy', category: 'health_wellness' },
      { id: 'mental_health_counseling', name: 'Mental Health Counseling', category: 'health_wellness' },
      { id: 'life_coaching', name: 'Life Coaching', category: 'health_wellness' },
      { id: 'stress_management', name: 'Stress Management', category: 'health_wellness' },
      { id: 'meditation_instruction', name: 'Meditation Instruction', category: 'health_wellness' },
      { id: 'mindfulness_training', name: 'Mindfulness Training', category: 'health_wellness' },
      { id: 'sleep_coaching', name: 'Sleep Coaching', category: 'health_wellness' },
      { id: 'habit_formation', name: 'Habit Formation', category: 'health_wellness' },
      { id: 'addiction_recovery', name: 'Addiction Recovery', category: 'health_wellness' },
      { id: 'smoking_cessation', name: 'Smoking Cessation', category: 'health_wellness' },
      { id: 'chronic_pain_management', name: 'Chronic Pain Management', category: 'health_wellness' },
      { id: 'diabetes_management', name: 'Diabetes Management', category: 'health_wellness' },
      { id: 'heart_health_programs', name: 'Heart Health Programs', category: 'health_wellness' },
      { id: 'womens_health', name: "Women's Health", category: 'health_wellness' },
      { id: 'mens_health', name: "Men's Health", category: 'health_wellness' },
      { id: 'senior_fitness', name: 'Senior Fitness', category: 'health_wellness' },
      { id: 'prenatal_fitness', name: 'Prenatal Fitness', category: 'health_wellness' },
      { id: 'postnatal_recovery', name: 'Postnatal Recovery', category: 'health_wellness' },
      { id: 'pediatric_health', name: 'Pediatric Health', category: 'health_wellness' },
      { id: 'teen_wellness', name: 'Teen Wellness', category: 'health_wellness' },
      { id: 'corporate_wellness', name: 'Corporate Wellness', category: 'health_wellness' },
      { id: 'workplace_ergonomics', name: 'Workplace Ergonomics', category: 'health_wellness' },
      { id: 'injury_prevention', name: 'Injury Prevention', category: 'health_wellness' },
      { id: 'mobility_training', name: 'Mobility Training', category: 'health_wellness' },
      { id: 'flexibility_coaching', name: 'Flexibility Coaching', category: 'health_wellness' },
      { id: 'strength_training', name: 'Strength Training', category: 'health_wellness' },
      { id: 'endurance_training', name: 'Endurance Training', category: 'health_wellness' },
      { id: 'marathon_coaching', name: 'Marathon Coaching', category: 'health_wellness' },
      { id: 'triathlon_training', name: 'Triathlon Training', category: 'health_wellness' },
      { id: 'bodybuilding_coaching', name: 'Bodybuilding Coaching', category: 'health_wellness' },
      { id: 'powerlifting_training', name: 'Powerlifting Training', category: 'health_wellness' },
      { id: 'functional_fitness', name: 'Functional Fitness', category: 'health_wellness' },
      { id: 'dance_fitness', name: 'Dance Fitness', category: 'health_wellness' },
      { id: 'martial_arts_training', name: 'Martial Arts Training', category: 'health_wellness' },
      { id: 'boxing_coaching', name: 'Boxing Coaching', category: 'health_wellness' },
      { id: 'swimming_instruction', name: 'Swimming Instruction', category: 'health_wellness' },
      { id: 'cycling_coaching', name: 'Cycling Coaching', category: 'health_wellness' },
      { id: 'hiking_outdoor_fitness', name: 'Hiking/Outdoor Fitness', category: 'health_wellness' },
      { id: 'adventure_fitness', name: 'Adventure Fitness', category: 'health_wellness' },
      { id: 'holistic_health', name: 'Holistic Health', category: 'health_wellness' },
      { id: 'integrative_medicine', name: 'Integrative Medicine', category: 'health_wellness' },
    ],
  },
  {
    id: 'education_training',
    name: 'Education & Training',
    emoji: '🎓',
    description: 'Online courses, tutoring, professional development',
    niches: [
      { id: 'online_course_creation', name: 'Online Course Creation', category: 'education_training' },
      { id: 'corporate_training', name: 'Corporate Training', category: 'education_training' },
      { id: 'leadership_development', name: 'Leadership Development', category: 'education_training' },
      { id: 'sales_training', name: 'Sales Training', category: 'education_training' },
      { id: 'customer_service_training', name: 'Customer Service Training', category: 'education_training' },
      { id: 'communication_skills', name: 'Communication Skills', category: 'education_training' },
      { id: 'public_speaking', name: 'Public Speaking', category: 'education_training' },
      { id: 'presentation_skills', name: 'Presentation Skills', category: 'education_training' },
      { id: 'writing_workshops', name: 'Writing Workshops', category: 'education_training' },
      { id: 'language_learning', name: 'Language Learning', category: 'education_training' },
      { id: 'test_prep_services', name: 'Test Prep Services', category: 'education_training' },
      { id: 'college_admissions_consulting', name: 'College Admissions Consulting', category: 'education_training' },
      { id: 'career_coaching', name: 'Career Coaching', category: 'education_training' },
      { id: 'resume_writing', name: 'Resume Writing', category: 'education_training' },
      { id: 'interview_preparation', name: 'Interview Preparation', category: 'education_training' },
      { id: 'job_search_strategy', name: 'Job Search Strategy', category: 'education_training' },
      { id: 'professional_development', name: 'Professional Development', category: 'education_training' },
      { id: 'executive_coaching', name: 'Executive Coaching', category: 'education_training' },
      { id: 'team_building', name: 'Team Building', category: 'education_training' },
      { id: 'conflict_resolution', name: 'Conflict Resolution', category: 'education_training' },
      { id: 'negotiation_training', name: 'Negotiation Training', category: 'education_training' },
      { id: 'time_management', name: 'Time Management', category: 'education_training' },
      { id: 'productivity_coaching', name: 'Productivity Coaching', category: 'education_training' },
      { id: 'project_management_training', name: 'Project Management Training', category: 'education_training' },
      { id: 'agile_scrum_training', name: 'Agile/Scrum Training', category: 'education_training' },
      { id: 'six_sigma_training', name: 'Six Sigma Training', category: 'education_training' },
      { id: 'lean_management', name: 'Lean Management', category: 'education_training' },
      { id: 'change_management', name: 'Change Management', category: 'education_training' },
      { id: 'innovation_training', name: 'Innovation Training', category: 'education_training' },
      { id: 'design_thinking_workshops', name: 'Design Thinking Workshops', category: 'education_training' },
      { id: 'creative_problem_solving', name: 'Creative Problem Solving', category: 'education_training' },
      { id: 'critical_thinking', name: 'Critical Thinking', category: 'education_training' },
      { id: 'emotional_intelligence', name: 'Emotional Intelligence', category: 'education_training' },
      { id: 'diversity_inclusion_training', name: 'Diversity & Inclusion Training', category: 'education_training' },
      { id: 'compliance_training', name: 'Compliance Training', category: 'education_training' },
      { id: 'safety_training', name: 'Safety Training', category: 'education_training' },
      { id: 'technical_skills_training', name: 'Technical Skills Training', category: 'education_training' },
      { id: 'software_training', name: 'Software Training', category: 'education_training' },
      { id: 'digital_literacy', name: 'Digital Literacy', category: 'education_training' },
      { id: 'coding_bootcamps', name: 'Coding Bootcamps', category: 'education_training' },
      { id: 'data_analytics_training', name: 'Data Analytics Training', category: 'education_training' },
      { id: 'cybersecurity_training', name: 'Cybersecurity Training', category: 'education_training' },
      { id: 'cloud_computing_training', name: 'Cloud Computing Training', category: 'education_training' },
      { id: 'ai_ml_education', name: 'AI/ML Education', category: 'education_training' },
      { id: 'music_lessons', name: 'Music Lessons', category: 'education_training' },
      { id: 'art_instruction', name: 'Art Instruction', category: 'education_training' },
      { id: 'photography_classes', name: 'Photography Classes', category: 'education_training' },
      { id: 'cooking_classes', name: 'Cooking Classes', category: 'education_training' },
      { id: 'craft_workshops', name: 'Craft Workshops', category: 'education_training' },
      { id: 'hobby_education', name: 'Hobby Education', category: 'education_training' },
    ],
  },
  {
    id: 'finance_legal',
    name: 'Finance & Legal',
    emoji: '💰',
    description: 'Financial planning, accounting, legal services',
    niches: [
      { id: 'financial_planning', name: 'Financial Planning', category: 'finance_legal' },
      { id: 'investment_advisory', name: 'Investment Advisory', category: 'finance_legal' },
      { id: 'retirement_planning', name: 'Retirement Planning', category: 'finance_legal' },
      { id: 'tax_preparation', name: 'Tax Preparation', category: 'finance_legal' },
      { id: 'tax_strategy', name: 'Tax Strategy', category: 'finance_legal' },
      { id: 'estate_planning', name: 'Estate Planning', category: 'finance_legal' },
      { id: 'wealth_management', name: 'Wealth Management', category: 'finance_legal' },
      { id: 'portfolio_management', name: 'Portfolio Management', category: 'finance_legal' },
      { id: 'risk_management', name: 'Risk Management', category: 'finance_legal' },
      { id: 'insurance_consulting', name: 'Insurance Consulting', category: 'finance_legal' },
      { id: 'mortgage_brokering', name: 'Mortgage Brokering', category: 'finance_legal' },
      { id: 'real_estate_investment', name: 'Real Estate Investment', category: 'finance_legal' },
      { id: 'property_management', name: 'Property Management', category: 'finance_legal' },
      { id: 'bookkeeping_services', name: 'Bookkeeping Services', category: 'finance_legal' },
      { id: 'accounting_services', name: 'Accounting Services', category: 'finance_legal' },
      { id: 'payroll_services', name: 'Payroll Services', category: 'finance_legal' },
      { id: 'cfo_services', name: 'CFO Services', category: 'finance_legal' },
      { id: 'financial_auditing', name: 'Financial Auditing', category: 'finance_legal' },
      { id: 'forensic_accounting', name: 'Forensic Accounting', category: 'finance_legal' },
      { id: 'bankruptcy_consulting', name: 'Bankruptcy Consulting', category: 'finance_legal' },
      { id: 'debt_management', name: 'Debt Management', category: 'finance_legal' },
      { id: 'credit_repair', name: 'Credit Repair', category: 'finance_legal' },
      { id: 'budget_coaching', name: 'Budget Coaching', category: 'finance_legal' },
      { id: 'savings_strategy', name: 'Savings Strategy', category: 'finance_legal' },
      { id: 'college_savings_planning', name: 'College Savings Planning', category: 'finance_legal' },
      { id: 'business_valuation', name: 'Business Valuation', category: 'finance_legal' },
      { id: 'ma_advisory', name: 'M&A Advisory', category: 'finance_legal' },
      { id: 'fundraising_consulting', name: 'Fundraising Consulting', category: 'finance_legal' },
      { id: 'venture_capital_advisory', name: 'Venture Capital Advisory', category: 'finance_legal' },
      { id: 'angel_investment_consulting', name: 'Angel Investment Consulting', category: 'finance_legal' },
      { id: 'crowdfunding_strategy', name: 'Crowdfunding Strategy', category: 'finance_legal' },
      { id: 'grant_writing', name: 'Grant Writing', category: 'finance_legal' },
      { id: 'legal_consulting', name: 'Legal Consulting', category: 'finance_legal' },
      { id: 'contract_review', name: 'Contract Review', category: 'finance_legal' },
      { id: 'intellectual_property', name: 'Intellectual Property', category: 'finance_legal' },
      { id: 'patent_services', name: 'Patent Services', category: 'finance_legal' },
      { id: 'trademark_services', name: 'Trademark Services', category: 'finance_legal' },
      { id: 'copyright_services', name: 'Copyright Services', category: 'finance_legal' },
      { id: 'business_law', name: 'Business Law', category: 'finance_legal' },
      { id: 'employment_law', name: 'Employment Law', category: 'finance_legal' },
      { id: 'real_estate_law', name: 'Real Estate Law', category: 'finance_legal' },
      { id: 'family_law', name: 'Family Law', category: 'finance_legal' },
      { id: 'immigration_law', name: 'Immigration Law', category: 'finance_legal' },
      { id: 'criminal_defense', name: 'Criminal Defense', category: 'finance_legal' },
      { id: 'personal_injury_law', name: 'Personal Injury Law', category: 'finance_legal' },
      { id: 'medical_malpractice', name: 'Medical Malpractice', category: 'finance_legal' },
      { id: 'compliance_consulting', name: 'Compliance Consulting', category: 'finance_legal' },
      { id: 'regulatory_affairs', name: 'Regulatory Affairs', category: 'finance_legal' },
      { id: 'privacy_law', name: 'Privacy Law (GDPR/CCPA)', category: 'finance_legal' },
      { id: 'litigation_support', name: 'Litigation Support', category: 'finance_legal' },
    ],
  },
  {
    id: 'creative_media',
    name: 'Creative & Media',
    emoji: '🎨',
    description: 'Design, content creation, photography, video production',
    niches: [
      { id: 'graphic_design', name: 'Graphic Design', category: 'creative_media' },
      { id: 'logo_design', name: 'Logo Design', category: 'creative_media' },
      { id: 'brand_identity_design', name: 'Brand Identity Design', category: 'creative_media' },
      { id: 'packaging_design', name: 'Packaging Design', category: 'creative_media' },
      { id: 'print_design', name: 'Print Design', category: 'creative_media' },
      { id: 'web_design', name: 'Web Design', category: 'creative_media' },
      { id: 'app_design', name: 'App Design', category: 'creative_media' },
      { id: 'illustration_services', name: 'Illustration Services', category: 'creative_media' },
      { id: 'animation_services', name: 'Animation Services', category: 'creative_media' },
      { id: 'motion_graphics', name: 'Motion Graphics', category: 'creative_media' },
      { id: 'video_production', name: 'Video Production', category: 'creative_media' },
      { id: 'video_editing', name: 'Video Editing', category: 'creative_media' },
      { id: 'cinematography', name: 'Cinematography', category: 'creative_media' },
      { id: 'photography_services', name: 'Photography Services', category: 'creative_media' },
      { id: 'photo_editing', name: 'Photo Editing', category: 'creative_media' },
      { id: 'audio_production', name: 'Audio Production', category: 'creative_media' },
      { id: 'podcast_production', name: 'Podcast Production', category: 'creative_media' },
      { id: 'music_production', name: 'Music Production', category: 'creative_media' },
      { id: 'sound_design', name: 'Sound Design', category: 'creative_media' },
      { id: 'voiceover_services', name: 'Voiceover Services', category: 'creative_media' },
      { id: 'scriptwriting', name: 'Scriptwriting', category: 'creative_media' },
      { id: 'screenwriting', name: 'Screenwriting', category: 'creative_media' },
      { id: 'novel_writing', name: 'Novel Writing', category: 'creative_media' },
      { id: 'ghostwriting', name: 'Ghostwriting', category: 'creative_media' },
      { id: 'editing_services', name: 'Editing Services', category: 'creative_media' },
      { id: 'proofreading_services', name: 'Proofreading Services', category: 'creative_media' },
      { id: 'translation_services', name: 'Translation Services', category: 'creative_media' },
      { id: 'localization_services', name: 'Localization Services', category: 'creative_media' },
      { id: 'transcription_services', name: 'Transcription Services', category: 'creative_media' },
      { id: 'subtitling_services', name: 'Subtitling Services', category: 'creative_media' },
      { id: '3d_modeling', name: '3D Modeling', category: 'creative_media' },
      { id: '3d_animation', name: '3D Animation', category: 'creative_media' },
      { id: 'cad_design', name: 'CAD Design', category: 'creative_media' },
      { id: 'architectural_visualization', name: 'Architectural Visualization', category: 'creative_media' },
      { id: 'product_rendering', name: 'Product Rendering', category: 'creative_media' },
      { id: 'game_art', name: 'Game Art', category: 'creative_media' },
      { id: 'character_design', name: 'Character Design', category: 'creative_media' },
      { id: 'concept_art', name: 'Concept Art', category: 'creative_media' },
      { id: 'storyboarding', name: 'Storyboarding', category: 'creative_media' },
      { id: 'comic_book_creation', name: 'Comic Book Creation', category: 'creative_media' },
      { id: 'manga_anime_art', name: 'Manga/Anime Art', category: 'creative_media' },
      { id: 'digital_painting', name: 'Digital Painting', category: 'creative_media' },
      { id: 'portrait_art', name: 'Portrait Art', category: 'creative_media' },
      { id: 'caricature_services', name: 'Caricature Services', category: 'creative_media' },
      { id: 'tattoo_design', name: 'Tattoo Design', category: 'creative_media' },
      { id: 'fashion_design', name: 'Fashion Design', category: 'creative_media' },
      { id: 'interior_design', name: 'Interior Design', category: 'creative_media' },
      { id: 'landscape_design', name: 'Landscape Design', category: 'creative_media' },
      { id: 'exhibition_design', name: 'Exhibition Design', category: 'creative_media' },
      { id: 'set_design', name: 'Set Design', category: 'creative_media' },
    ],
  },
  {
    id: 'ecommerce_retail',
    name: 'E-commerce & Retail',
    emoji: '🛍️',
    description: 'Online stores, product sales, retail consulting',
    niches: [
      { id: 'dropshipping_consulting', name: 'Dropshipping Consulting', category: 'ecommerce_retail' },
      { id: 'amazon_fba_consulting', name: 'Amazon FBA Consulting', category: 'ecommerce_retail' },
      { id: 'shopify_store_setup', name: 'Shopify Store Setup', category: 'ecommerce_retail' },
      { id: 'ecommerce_strategy', name: 'E-commerce Strategy', category: 'ecommerce_retail' },
      { id: 'product_sourcing', name: 'Product Sourcing', category: 'ecommerce_retail' },
      { id: 'supplier_management', name: 'Supplier Management', category: 'ecommerce_retail' },
      { id: 'inventory_management', name: 'Inventory Management', category: 'ecommerce_retail' },
      { id: 'order_fulfillment', name: 'Order Fulfillment', category: 'ecommerce_retail' },
      { id: 'shipping_optimization', name: 'Shipping Optimization', category: 'ecommerce_retail' },
      { id: 'returns_management', name: 'Returns Management', category: 'ecommerce_retail' },
      { id: 'customer_service_outsourcing', name: 'Customer Service Outsourcing', category: 'ecommerce_retail' },
      { id: 'product_photography', name: 'Product Photography', category: 'ecommerce_retail' },
      { id: 'product_description_writing', name: 'Product Description Writing', category: 'ecommerce_retail' },
      { id: 'pricing_strategy', name: 'Pricing Strategy', category: 'ecommerce_retail' },
      { id: 'competitive_analysis_retail', name: 'Competitive Analysis', category: 'ecommerce_retail' },
      { id: 'market_research_retail', name: 'Market Research', category: 'ecommerce_retail' },
      { id: 'trend_forecasting', name: 'Trend Forecasting', category: 'ecommerce_retail' },
      { id: 'product_development', name: 'Product Development', category: 'ecommerce_retail' },
      { id: 'private_label_consulting', name: 'Private Label Consulting', category: 'ecommerce_retail' },
      { id: 'white_label_services', name: 'White Label Services', category: 'ecommerce_retail' },
      { id: 'wholesale_consulting', name: 'Wholesale Consulting', category: 'ecommerce_retail' },
      { id: 'retail_strategy', name: 'Retail Strategy', category: 'ecommerce_retail' },
      { id: 'store_layout_design', name: 'Store Layout Design', category: 'ecommerce_retail' },
      { id: 'visual_merchandising', name: 'Visual Merchandising', category: 'ecommerce_retail' },
      { id: 'point_of_sale_systems', name: 'Point of Sale Systems', category: 'ecommerce_retail' },
      { id: 'retail_analytics', name: 'Retail Analytics', category: 'ecommerce_retail' },
      { id: 'loss_prevention', name: 'Loss Prevention', category: 'ecommerce_retail' },
      { id: 'loyalty_program_design', name: 'Loyalty Program Design', category: 'ecommerce_retail' },
      { id: 'gift_card_programs', name: 'Gift Card Programs', category: 'ecommerce_retail' },
      { id: 'subscription_box_services', name: 'Subscription Box Services', category: 'ecommerce_retail' },
      { id: 'membership_programs', name: 'Membership Programs', category: 'ecommerce_retail' },
      { id: 'marketplace_management', name: 'Marketplace Management', category: 'ecommerce_retail' },
      { id: 'multi_channel_selling', name: 'Multi-channel Selling', category: 'ecommerce_retail' },
      { id: 'cross_border_ecommerce', name: 'Cross-border E-commerce', category: 'ecommerce_retail' },
      { id: 'international_expansion', name: 'International Expansion', category: 'ecommerce_retail' },
      { id: 'payment_processing', name: 'Payment Processing', category: 'ecommerce_retail' },
      { id: 'fraud_prevention', name: 'Fraud Prevention', category: 'ecommerce_retail' },
      { id: 'conversion_optimization', name: 'Conversion Optimization', category: 'ecommerce_retail' },
      { id: 'cart_abandonment_solutions', name: 'Cart Abandonment Solutions', category: 'ecommerce_retail' },
      { id: 'email_automation_ecommerce', name: 'Email Automation for E-commerce', category: 'ecommerce_retail' },
      { id: 'sms_marketing', name: 'SMS Marketing', category: 'ecommerce_retail' },
      { id: 'influencer_partnerships', name: 'Influencer Partnerships', category: 'ecommerce_retail' },
      { id: 'affiliate_programs', name: 'Affiliate Programs', category: 'ecommerce_retail' },
      { id: 'customer_lifetime_value', name: 'Customer Lifetime Value Optimization', category: 'ecommerce_retail' },
      { id: 'personalization_engines', name: 'Personalization Engines', category: 'ecommerce_retail' },
      { id: 'product_recommendations', name: 'Product Recommendations', category: 'ecommerce_retail' },
      { id: 'upselling_crossselling', name: 'Upselling & Cross-selling', category: 'ecommerce_retail' },
      { id: 'customer_reviews_management', name: 'Customer Reviews Management', category: 'ecommerce_retail' },
      { id: 'social_commerce', name: 'Social Commerce', category: 'ecommerce_retail' },
      { id: 'live_shopping', name: 'Live Shopping', category: 'ecommerce_retail' },
    ],
  },
  {
    id: 'hospitality_travel',
    name: 'Hospitality & Travel',
    emoji: '✈️',
    description: 'Hotels, restaurants, travel planning, event services',
    niches: [
      { id: 'travel_planning', name: 'Travel Planning', category: 'hospitality_travel' },
      { id: 'event_planning', name: 'Event Planning', category: 'hospitality_travel' },
      { id: 'restaurant_management', name: 'Restaurant Management', category: 'hospitality_travel' },
      { id: 'hotel_services', name: 'Hotel Services', category: 'hospitality_travel' },
      { id: 'tour_operations', name: 'Tour Operations', category: 'hospitality_travel' },
      { id: 'vacation_rentals', name: 'Vacation Rentals', category: 'hospitality_travel' },
      { id: 'destination_management', name: 'Destination Management', category: 'hospitality_travel' },
      { id: 'corporate_travel', name: 'Corporate Travel', category: 'hospitality_travel' },
      { id: 'luxury_travel', name: 'Luxury Travel', category: 'hospitality_travel' },
      { id: 'adventure_travel', name: 'Adventure Travel', category: 'hospitality_travel' },
      { id: 'eco_tourism', name: 'Eco-Tourism', category: 'hospitality_travel' },
      { id: 'cruise_planning', name: 'Cruise Planning', category: 'hospitality_travel' },
      { id: 'honeymoon_planning', name: 'Honeymoon Planning', category: 'hospitality_travel' },
      { id: 'group_travel', name: 'Group Travel', category: 'hospitality_travel' },
      { id: 'study_abroad', name: 'Study Abroad', category: 'hospitality_travel' },
      { id: 'visa_assistance', name: 'Visa Assistance', category: 'hospitality_travel' },
      { id: 'wedding_planning', name: 'Wedding Planning', category: 'hospitality_travel' },
      { id: 'conference_planning', name: 'Conference Planning', category: 'hospitality_travel' },
      { id: 'trade_show_management', name: 'Trade Show Management', category: 'hospitality_travel' },
      { id: 'catering_services', name: 'Catering Services', category: 'hospitality_travel' },
      { id: 'food_truck_consulting', name: 'Food Truck Consulting', category: 'hospitality_travel' },
      { id: 'bar_consulting', name: 'Bar Consulting', category: 'hospitality_travel' },
      { id: 'nightclub_management', name: 'Nightclub Management', category: 'hospitality_travel' },
      { id: 'venue_management', name: 'Venue Management', category: 'hospitality_travel' },
      { id: 'theme_park_services', name: 'Theme Park Services', category: 'hospitality_travel' },
      { id: 'spa_management', name: 'Spa Management', category: 'hospitality_travel' },
      { id: 'resort_operations', name: 'Resort Operations', category: 'hospitality_travel' },
      { id: 'bed_breakfast', name: 'Bed & Breakfast', category: 'hospitality_travel' },
      { id: 'hostel_management', name: 'Hostel Management', category: 'hospitality_travel' },
      { id: 'airbnb_optimization', name: 'Airbnb Optimization', category: 'hospitality_travel' },
      { id: 'guest_experience', name: 'Guest Experience', category: 'hospitality_travel' },
      { id: 'concierge_services', name: 'Concierge Services', category: 'hospitality_travel' },
      { id: 'housekeeping_services', name: 'Housekeeping Services', category: 'hospitality_travel' },
      { id: 'culinary_consulting', name: 'Culinary Consulting', category: 'hospitality_travel' },
      { id: 'menu_engineering', name: 'Menu Engineering', category: 'hospitality_travel' },
      { id: 'wine_consulting', name: 'Wine Consulting', category: 'hospitality_travel' },
      { id: 'beverage_programs', name: 'Beverage Programs', category: 'hospitality_travel' },
      { id: 'food_safety', name: 'Food Safety', category: 'hospitality_travel' },
      { id: 'restaurant_design', name: 'Restaurant Design', category: 'hospitality_travel' },
      { id: 'hospitality_training', name: 'Hospitality Training', category: 'hospitality_travel' },
      { id: 'customer_service_hospitality', name: 'Customer Service (Hospitality)', category: 'hospitality_travel' },
      { id: 'revenue_management', name: 'Revenue Management', category: 'hospitality_travel' },
      { id: 'yield_management', name: 'Yield Management', category: 'hospitality_travel' },
      { id: 'booking_optimization', name: 'Booking Optimization', category: 'hospitality_travel' },
      { id: 'online_reputation_hospitality', name: 'Online Reputation Management', category: 'hospitality_travel' },
      { id: 'loyalty_programs_hospitality', name: 'Loyalty Programs', category: 'hospitality_travel' },
      { id: 'package_design', name: 'Package Design', category: 'hospitality_travel' },
      { id: 'seasonal_offerings', name: 'Seasonal Offerings', category: 'hospitality_travel' },
      { id: 'special_events', name: 'Special Events', category: 'hospitality_travel' },
      { id: 'sustainability_hospitality', name: 'Sustainability in Hospitality', category: 'hospitality_travel' },
    ],
  },
  {
    id: 'personal_services',
    name: 'Personal Services',
    emoji: '🤝',
    description: 'Coaching, virtual assistance, personal care',
    niches: [
      { id: 'life_coaching_personal', name: 'Life Coaching', category: 'personal_services' },
      { id: 'career_counseling', name: 'Career Counseling', category: 'personal_services' },
      { id: 'virtual_assistance', name: 'Virtual Assistance', category: 'personal_services' },
      { id: 'pet_care_services', name: 'Pet Care Services', category: 'personal_services' },
      { id: 'home_organization', name: 'Home Organization', category: 'personal_services' },
      { id: 'personal_shopping', name: 'Personal Shopping', category: 'personal_services' },
      { id: 'styling_services', name: 'Styling Services', category: 'personal_services' },
      { id: 'wardrobe_consulting', name: 'Wardrobe Consulting', category: 'personal_services' },
      { id: 'image_consulting', name: 'Image Consulting', category: 'personal_services' },
      { id: 'etiquette_training', name: 'Etiquette Training', category: 'personal_services' },
      { id: 'dating_coaching', name: 'Dating Coaching', category: 'personal_services' },
      { id: 'relationship_coaching', name: 'Relationship Coaching', category: 'personal_services' },
      { id: 'marriage_counseling', name: 'Marriage Counseling', category: 'personal_services' },
      { id: 'family_therapy', name: 'Family Therapy', category: 'personal_services' },
      { id: 'parenting_coaching', name: 'Parenting Coaching', category: 'personal_services' },
      { id: 'childcare_services', name: 'Childcare Services', category: 'personal_services' },
      { id: 'nanny_services', name: 'Nanny Services', category: 'personal_services' },
      { id: 'tutoring_services', name: 'Tutoring Services', category: 'personal_services' },
      { id: 'academic_coaching', name: 'Academic Coaching', category: 'personal_services' },
      { id: 'homework_help', name: 'Homework Help', category: 'personal_services' },
      { id: 'personal_chef', name: 'Personal Chef', category: 'personal_services' },
      { id: 'meal_planning', name: 'Meal Planning', category: 'personal_services' },
      { id: 'meal_prep_services', name: 'Meal Prep Services', category: 'personal_services' },
      { id: 'grocery_shopping', name: 'Grocery Shopping', category: 'personal_services' },
      { id: 'errand_services', name: 'Errand Services', category: 'personal_services' },
      { id: 'personal_concierge', name: 'Personal Concierge', category: 'personal_services' },
      { id: 'house_sitting', name: 'House Sitting', category: 'personal_services' },
      { id: 'pet_sitting', name: 'Pet Sitting', category: 'personal_services' },
      { id: 'dog_walking', name: 'Dog Walking', category: 'personal_services' },
      { id: 'pet_training', name: 'Pet Training', category: 'personal_services' },
      { id: 'pet_grooming', name: 'Pet Grooming', category: 'personal_services' },
      { id: 'house_cleaning', name: 'House Cleaning', category: 'personal_services' },
      { id: 'laundry_services', name: 'Laundry Services', category: 'personal_services' },
      { id: 'dry_cleaning', name: 'Dry Cleaning', category: 'personal_services' },
      { id: 'tailoring_services', name: 'Tailoring Services', category: 'personal_services' },
      { id: 'shoe_repair', name: 'Shoe Repair', category: 'personal_services' },
      { id: 'handyman_services', name: 'Handyman Services', category: 'personal_services' },
      { id: 'lawn_care', name: 'Lawn Care', category: 'personal_services' },
      { id: 'landscaping', name: 'Landscaping', category: 'personal_services' },
      { id: 'pool_maintenance', name: 'Pool Maintenance', category: 'personal_services' },
      { id: 'moving_services', name: 'Moving Services', category: 'personal_services' },
      { id: 'packing_services', name: 'Packing Services', category: 'personal_services' },
      { id: 'storage_solutions', name: 'Storage Solutions', category: 'personal_services' },
      { id: 'senior_care', name: 'Senior Care', category: 'personal_services' },
      { id: 'home_health_care', name: 'Home Health Care', category: 'personal_services' },
      { id: 'medical_transportation', name: 'Medical Transportation', category: 'personal_services' },
      { id: 'driver_services', name: 'Driver Services', category: 'personal_services' },
      { id: 'chauffeur_services', name: 'Chauffeur Services', category: 'personal_services' },
      { id: 'car_detailing', name: 'Car Detailing', category: 'personal_services' },
      { id: 'mobile_services', name: 'Mobile Services', category: 'personal_services' },
    ],
  },
  {
    id: 'real_estate',
    name: 'Real Estate',
    emoji: '🏡',
    description: 'Property sales, management, investment',
    niches: [
      { id: 'residential_real_estate', name: 'Residential Real Estate', category: 'real_estate' },
      { id: 'commercial_real_estate', name: 'Commercial Real Estate', category: 'real_estate' },
      { id: 'luxury_real_estate', name: 'Luxury Real Estate', category: 'real_estate' },
      { id: 'vacation_properties', name: 'Vacation Properties', category: 'real_estate' },
      { id: 'investment_properties', name: 'Investment Properties', category: 'real_estate' },
      { id: 'property_flipping', name: 'Property Flipping', category: 'real_estate' },
      { id: 'real_estate_development', name: 'Real Estate Development', category: 'real_estate' },
      { id: 'land_sales', name: 'Land Sales', category: 'real_estate' },
      { id: 'farm_ranch', name: 'Farm & Ranch', category: 'real_estate' },
      { id: 'industrial_properties', name: 'Industrial Properties', category: 'real_estate' },
      { id: 'retail_spaces', name: 'Retail Spaces', category: 'real_estate' },
      { id: 'office_spaces', name: 'Office Spaces', category: 'real_estate' },
      { id: 'multifamily_properties', name: 'Multifamily Properties', category: 'real_estate' },
      { id: 'condos_townhomes', name: 'Condos & Townhomes', category: 'real_estate' },
      { id: 'new_construction', name: 'New Construction', category: 'real_estate' },
      { id: 'foreclosures', name: 'Foreclosures', category: 'real_estate' },
      { id: 'short_sales', name: 'Short Sales', category: 'real_estate' },
      { id: 'relocation_services', name: 'Relocation Services', category: 'real_estate' },
      { id: 'first_time_buyers', name: 'First-Time Buyers', category: 'real_estate' },
      { id: 'downsizing', name: 'Downsizing', category: 'real_estate' },
      { id: 'senior_living', name: 'Senior Living', category: 'real_estate' },
      { id: '55_communities', name: '55+ Communities', category: 'real_estate' },
      { id: 'gated_communities', name: 'Gated Communities', category: 'real_estate' },
      { id: 'waterfront_properties', name: 'Waterfront Properties', category: 'real_estate' },
      { id: 'golf_course_properties', name: 'Golf Course Properties', category: 'real_estate' },
      { id: 'equestrian_properties', name: 'Equestrian Properties', category: 'real_estate' },
      { id: 'green_homes', name: 'Green Homes', category: 'real_estate' },
      { id: 'smart_homes', name: 'Smart Homes', category: 'real_estate' },
      { id: 'historic_properties', name: 'Historic Properties', category: 'real_estate' },
      { id: 'international_real_estate', name: 'International Real Estate', category: 'real_estate' },
      { id: 'property_management_re', name: 'Property Management', category: 'real_estate' },
      { id: 'hoa_management', name: 'HOA Management', category: 'real_estate' },
      { id: 'tenant_placement', name: 'Tenant Placement', category: 'real_estate' },
      { id: 'lease_administration', name: 'Lease Administration', category: 'real_estate' },
      { id: 'rent_collection', name: 'Rent Collection', category: 'real_estate' },
      { id: 'maintenance_coordination', name: 'Maintenance Coordination', category: 'real_estate' },
      { id: 'eviction_services', name: 'Eviction Services', category: 'real_estate' },
      { id: 'real_estate_staging', name: 'Real Estate Staging', category: 'real_estate' },
      { id: 'real_estate_photography', name: 'Real Estate Photography', category: 'real_estate' },
      { id: 'virtual_tours', name: 'Virtual Tours', category: 'real_estate' },
      { id: 'drone_photography', name: 'Drone Photography', category: 'real_estate' },
      { id: 'real_estate_marketing', name: 'Real Estate Marketing', category: 'real_estate' },
      { id: 'open_house_services', name: 'Open House Services', category: 'real_estate' },
      { id: 'buyer_representation', name: 'Buyer Representation', category: 'real_estate' },
      { id: 'seller_representation', name: 'Seller Representation', category: 'real_estate' },
      { id: 'dual_agency', name: 'Dual Agency', category: 'real_estate' },
      { id: 'real_estate_appraisal', name: 'Real Estate Appraisal', category: 'real_estate' },
      { id: 'home_inspection', name: 'Home Inspection', category: 'real_estate' },
      { id: 'title_services', name: 'Title Services', category: 'real_estate' },
      { id: 'escrow_services', name: 'Escrow Services', category: 'real_estate' },
    ],
  },
  {
    id: 'automotive',
    name: 'Automotive',
    emoji: '🚗',
    description: 'Car sales, repair, detailing, consulting',
    niches: [
      { id: 'auto_sales', name: 'Auto Sales', category: 'automotive' },
      { id: 'luxury_auto_sales', name: 'Luxury Auto Sales', category: 'automotive' },
      { id: 'used_car_sales', name: 'Used Car Sales', category: 'automotive' },
      { id: 'classic_cars', name: 'Classic Cars', category: 'automotive' },
      { id: 'exotic_cars', name: 'Exotic Cars', category: 'automotive' },
      { id: 'electric_vehicles', name: 'Electric Vehicles', category: 'automotive' },
      { id: 'hybrid_vehicles', name: 'Hybrid Vehicles', category: 'automotive' },
      { id: 'motorcycles', name: 'Motorcycles', category: 'automotive' },
      { id: 'rvs_motorhomes', name: 'RVs & Motorhomes', category: 'automotive' },
      { id: 'boats_watercraft', name: 'Boats & Watercraft', category: 'automotive' },
      { id: 'commercial_vehicles', name: 'Commercial Vehicles', category: 'automotive' },
      { id: 'fleet_management', name: 'Fleet Management', category: 'automotive' },
      { id: 'auto_repair', name: 'Auto Repair', category: 'automotive' },
      { id: 'auto_maintenance', name: 'Auto Maintenance', category: 'automotive' },
      { id: 'brake_services', name: 'Brake Services', category: 'automotive' },
      { id: 'tire_services', name: 'Tire Services', category: 'automotive' },
      { id: 'oil_change', name: 'Oil Change', category: 'automotive' },
      { id: 'transmission_repair', name: 'Transmission Repair', category: 'automotive' },
      { id: 'engine_repair', name: 'Engine Repair', category: 'automotive' },
      { id: 'electrical_systems', name: 'Electrical Systems', category: 'automotive' },
      { id: 'air_conditioning', name: 'Air Conditioning', category: 'automotive' },
      { id: 'diagnostics', name: 'Diagnostics', category: 'automotive' },
      { id: 'collision_repair', name: 'Collision Repair', category: 'automotive' },
      { id: 'auto_body_work', name: 'Auto Body Work', category: 'automotive' },
      { id: 'paint_services', name: 'Paint Services', category: 'automotive' },
      { id: 'dent_removal', name: 'Dent Removal', category: 'automotive' },
      { id: 'windshield_repair', name: 'Windshield Repair', category: 'automotive' },
      { id: 'auto_detailing_services', name: 'Auto Detailing', category: 'automotive' },
      { id: 'car_wash_services', name: 'Car Wash', category: 'automotive' },
      { id: 'mobile_detailing', name: 'Mobile Detailing', category: 'automotive' },
      { id: 'ceramic_coating', name: 'Ceramic Coating', category: 'automotive' },
      { id: 'paint_protection', name: 'Paint Protection', category: 'automotive' },
      { id: 'window_tinting', name: 'Window Tinting', category: 'automotive' },
      { id: 'auto_customization', name: 'Auto Customization', category: 'automotive' },
      { id: 'performance_tuning', name: 'Performance Tuning', category: 'automotive' },
      { id: 'aftermarket_parts', name: 'Aftermarket Parts', category: 'automotive' },
      { id: 'auto_accessories', name: 'Auto Accessories', category: 'automotive' },
      { id: 'car_audio', name: 'Car Audio', category: 'automotive' },
      { id: 'security_systems', name: 'Security Systems', category: 'automotive' },
      { id: 'gps_navigation', name: 'GPS Navigation', category: 'automotive' },
      { id: 'towing_services', name: 'Towing Services', category: 'automotive' },
      { id: 'roadside_assistance', name: 'Roadside Assistance', category: 'automotive' },
      { id: 'auto_insurance', name: 'Auto Insurance', category: 'automotive' },
      { id: 'auto_financing', name: 'Auto Financing', category: 'automotive' },
      { id: 'lease_consulting', name: 'Lease Consulting', category: 'automotive' },
      { id: 'trade_in_services', name: 'Trade-In Services', category: 'automotive' },
      { id: 'vehicle_inspection', name: 'Vehicle Inspection', category: 'automotive' },
      { id: 'pre_purchase_inspection', name: 'Pre-Purchase Inspection', category: 'automotive' },
      { id: 'vehicle_history_reports', name: 'Vehicle History Reports', category: 'automotive' },
      { id: 'auto_consulting', name: 'Auto Consulting', category: 'automotive' },
    ],
  },
];

// Helper functions
export const getAllNiches = (): Niche[] => {
  return FORGE_INDUSTRY_CATEGORIES.flatMap((category) => category.niches);
};

export const getNichesByCategory = (categoryId: string): Niche[] => {
  const category = FORGE_INDUSTRY_CATEGORIES.find((cat) => cat.id === categoryId);
  return category ? category.niches : [];
};

export const getCategoryById = (categoryId: string): IndustryCategory | undefined => {
  return FORGE_INDUSTRY_CATEGORIES.find((cat) => cat.id === categoryId);
};

export const searchNiches = (query: string): Niche[] => {
  const lowerQuery = query.toLowerCase();
  return getAllNiches().filter(
    (niche) =>
      niche.name.toLowerCase().includes(lowerQuery) ||
      niche.category.toLowerCase().includes(lowerQuery)
  );
};
